# HAPIE Docker Setup Script (Windows)

Write-Host '==================================================' -ForegroundColor Cyan
Write-Host 'HAPIE - Docker Setup' -ForegroundColor Cyan
Write-Host '==================================================' -ForegroundColor Cyan

# Check if Docker is running
try {
    docker info | Out-Null
    Write-Host '✓ Docker is running' -ForegroundColor Green
} catch {
    Write-Host '❌ Docker is not running. Please start Docker Desktop.' -ForegroundColor Red
    exit 1
}

# Detect HOST HARDWARE PROFILE
Write-Host ''
Write-Host 'Detecting host hardware profile...' -ForegroundColor Cyan

$comp = Get-CimInstance Win32_ComputerSystem
$proc = Get-CimInstance Win32_Processor | Select-Object -First 1

$ram_gb = [Math]::Round($comp.TotalPhysicalMemory / 1GB, 1)
$logical_cpus = $comp.NumberOfLogicalProcessors
$physical_cores = $proc.NumberOfCores
$cpu_name = $proc.Name.Trim()

# Build .env content
$env_lines = @(
    '# Generated by docker-setup.ps1',
    "HAPIE_HOST_TOTAL_RAM_GB=$ram_gb",
    "HAPIE_HOST_CPU_CORES=$physical_cores",
    "HAPIE_HOST_CPU_THREADS=$logical_cpus",
    "HAPIE_HOST_CPU_BRAND=$cpu_name"
)

# Write to .env file
$env_lines | Out-File -FilePath '.env' -Encoding utf8 -Force

# Set in current environment session
$env:HAPIE_HOST_TOTAL_RAM_GB = "$ram_gb"
$env:HAPIE_HOST_CPU_CORES = "$physical_cores"
$env:HAPIE_HOST_CPU_THREADS = "$logical_cpus"
$env:HAPIE_HOST_CPU_BRAND = "$cpu_name"

Write-Host "✓ Detected Host: $cpu_name" -ForegroundColor Green
Write-Host "✓ Hardware Profile: $ram_gb GB RAM, $logical_cpus Logicals" -ForegroundColor Green
Write-Host '✓ Environment saved to .env' -ForegroundColor Gray

# Build and start services
Write-Host ''
Write-Host 'Building Docker images...' -ForegroundColor Yellow
docker-compose --env-file .env build

Write-Host ''
Write-Host 'Starting HAPIE services...' -ForegroundColor Yellow
docker-compose --env-file .env up -d

Write-Host ''
Write-Host 'Waiting for backend to be ready...' -ForegroundColor Yellow
Start-Sleep -Seconds 5

# Check if backend is healthy
try {
    $resp = Invoke-WebRequest -Uri 'http://localhost:8000/health' -UseBasicParsing
    Write-Host '✓ Backend is running at http://localhost:8000' -ForegroundColor Green
} catch {
    Write-Host '⚠ Backend may still be starting. Check logs with: docker-compose logs backend' -ForegroundColor Yellow
}

Write-Host ''
Write-Host '==================================================' -ForegroundColor Cyan
Write-Host 'HAPIE is running!' -ForegroundColor Green
Write-Host '==================================================' -ForegroundColor Cyan
Write-Host ''
Write-Host 'Backend API: http://localhost:8000' -ForegroundColor White
Write-Host 'API Docs: http://localhost:8000/docs' -ForegroundColor White
Write-Host ''
Write-Host 'To setup base model, run:' -ForegroundColor Yellow
Write-Host '  docker-compose exec backend python setup.py'
Write-Host ''
